# p1/Vagrantfile

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # Désactive le provider par défaut
  config.vm.provider :virtualbox do |vb|
    vb.gui = false
  end

  ## Machine 1 : K3s Server
  config.vm.define "sben-tayS" do |srv|
    srv.vm.hostname = "sben-tayS"
    srv.vm.network "private_network", ip: "192.168.56.110"

    srv.vm.provider :virtualbox do |hv|
      hv.cpus = 1
      hv.memory = 1024
    end

    srv.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end

  ## Machine 2 : K3s Worker
  config.vm.define "sben-taySW" do |wrk|
    wrk.vm.hostname = "sben-taySW"
    wrk.vm.network "private_network", ip: "192.168.56.111"

    wrk.vm.provider :virtualbox do |hv|
      hv.cpus = 1
      hv.memory = 1024
    end

    wrk.vm.provision "shell", path: "scripts/install_k3s_worker.sh"
  end
end
