Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian11"
  
  config.vm.define "sben-tayS" do |server|
    server.vm.hostname = "sben-tayS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "libvirt" do |v|
      v.memory = 2048
      v.cpus = 2
    end
    
    server.vm.synced_folder ".", "/vagrant", type: "rsync"
    
    server.vm.provision "shell", path: "scripts/install_k3d_argocd.sh"
  end
end
